stages:
- name: build
  steps:
  - runScriptConfig:
      image: harbor.ctn.prevnet/library/golang:latest
      shellScript: go build -o app
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: harbor.ctn.prevnet/paulovigne/hellogo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.ctn.prevnet
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
notification: {}
