apiVersion: v1
kind: Namespace
metadata:
  name: hellogo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellogo
  namespace: hellogo
spec:
  rules:
  - host: hellogo-diat.prevnet
    http:
      paths:
      - backend:
          serviceName: hellogo-http
          servicePort: tcp-8080
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: hellogo-http
  namespace: hellogo
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: tcp-8080
  selector:
    app: account-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  namespace: hellogo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hellogo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hellogo
        version: "1.0"
    spec:
      containers:
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        name: hellogo
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: harbor
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
